export enum ICONS {
  close = 'close',
  bookmark = 'bookmark',
  list = 'list',
  home = 'home',
  chevronRight = 'chevron-right',
  chevronLeft = 'chevron-left',
  arrowLeft = 'arrow-left',
  camera = 'camera',
  chevronDown = 'chevron-down',
  chevronUp = 'chevron-up',
  info = 'info',
  alertTriangle = 'alert-triangle',
  checkCircle = 'check-circle',
}
