export default Object.freeze({
    SPLASH_SCREEN: 'SPLASH_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    HOME_SCREEN: 'HOME_SCREEN',
    FETCH_DATA_SCREEN: 'FETCH_DATA_SCREEN',
    FORM_SCREEN: 'FORM_SCREEN',

    MAIN_TABS_ROOT: 'MAIN_TABS_ROOT',
    MAIN_DRAWER_ROOT: 'MAIN_DRAWER_ROOT',

    ALERT: 'ALERT', // Do not redirect!
});
